name: 'action-ebuild-release'
description: 'Create / update an ebuild in a repository'
inputs:
  overlay:
    description: 'The overlay repository to operate on'
    required: true
  overlay_branch:
    description: 'The repository branch operate on'
    required: false 
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'package'
  color: 'purple'