name: 'action-ebuild-release'
description: 'Create / update an ebuild in a repository'
inputs:
  auth_token:
    description: 'The authentiation token to use when creating pull requests.'
    required: true
  deploy_key:
    description: 'The deploy key used when accessing the overlay repository.'
    required: true
  overlay_repo:
    description: 'The overlay repository to operate on (eg. hacking-gentoo/overlay)'
    required: true
  overlay_branch:
    description: 'The repository branch to operate on. If none specified a topic branch named after the category/package will be used.'
    required: false
  package_only:
    description: 'This is a package only ebuild for upstream source code.'
    required: false
    default: false
runs:
  using: 'composite'
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - name: Run action entrypoint
      run: entrypoint.sh
      shell: bash
